### ISSUE TITLE
CJK font styles

### ISSUE THREAD

**Issue by clkao** [alphagov/static#464]
https://github.com/alphagov/government-service-design-manual/blob/master/_includes/stylesheets/whitehall/_font-stacks.scss defines the font-family globally, however for the press releasees in CJK, the fonts look very weird on Mac: (Note the 兰 and 独 characters are particularly thin and inconsistent with others)

![2014-09-20 8 43 32](https://cloud.githubusercontent.com/assets/69736/4343695/3a4b6710-405f-11e4-9363-9dcdaf97357b.png)
(https://www.gov.uk/government/news/scottish-independence-referendum-statement-by-the-prime-minister.zh)
![2014-09-20 8 43 22](https://cloud.githubusercontent.com/assets/69736/4343696/3a7903aa-405f-11e4-8610-b472b38c3e3d.png)
(https://www.gov.uk/government/news/scottish-independence-referendum-statement-by-the-prime-minister.ja)

The suggested way is to decorate the html with with lang="zh" and lang="ja", and add different language-specific css styles for sans fonts, such as:

```
[lang="zh"] {
  font-family: 'Lantinghei TC'
}
```

For a portable full list of sans-serif font-family suitable for CJK, see also https://github.com/ethantw/Han/blob/master/sass/han/ff/_heiti.scss

**Comment by robinwhittleton** [comment]
I can no longer replicate this on either of the examples given on OS X 10.11. Don’t think we’ve changed anything that would mitigate the problem since the issue was raised, so an OS level bug that was fixed perhaps?
![screen shot 2016-07-26 at 10 22 28](https://cloud.githubusercontent.com/assets/7414/17132726/e8ae7cd2-531a-11e6-8c30-5d7bdc98eda3.png)
![screen shot 2016-07-26 at 10 22 39](https://cloud.githubusercontent.com/assets/7414/17132728/e8d82e6a-531a-11e6-9097-443174c9f943.png)

**Comment by clkao** [comment]
Hi, this appears to be fixed indeed.
