### ISSUE TITLE
Mixins within `/styleguide` appear to duplicate tookit

### ISSUE THREAD

**Issue by fofr** [alphagov/static#706]
It's not clear what the files in this directory are for.
- The typography mixins appear to duplicate the frontend toolkit ones here: https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_typography.scss
- The print mixin is looks like something that should be provided by the toolkit
- Font stacks looks like a duplication of https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_font_stack.scss

**Comment by tombye** [comment]
From memory, they used to be there to allow the toolkit mixins to be overwritten at the app level which is why they have copies of `_typography.scss` and `_font_stack.scss`. I think the need was to be able to make app-level changes first before these graduated to the toolkit.

The folder also contained variants for toolkit mixins, such as `_conditionals2.scss` which is [still in use](https://github.com/alphagov/static/blob/master/app/assets/stylesheets/static.scss#L7). This file which exists because mainstream pages started using a 'Desktop-down' approach to responsive design (this was a long time ago) so the 'mobile-up' approach of the toolkit was to be phased in while those pages were converted.

I don't think `_typography.scss` and `_font_stack.scss` are still used anywhere (though this could do with some grep'ing to check).

It's worth noting this pattern also exists in the [govuk_template Sass](https://github.com/alphagov/govuk_template/tree/master/source/assets/stylesheets/styleguide).

I agree about the print mixin, I think this should have moved some time ago.

**Comment by tijmenb** [comment]
If this is still the case it will probably be solved by architectural work to remove static (https://trello.com/c/zLiC5VwG) and adopting GOV.UK Frontend (https://trello.com/c/kzsj0ta0).
