### ISSUE TITLE
Layout for feedback slightly broken

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/static#998]
The layout for 'Is there something wrong with this page' is slightly off - it's indented too far.

Screenshot:
![screen shot 2017-04-11 at 12 06 31](https://cloud.githubusercontent.com/assets/2204224/24906392/6c8cb630-1eaf-11e7-9074-674ef1f6e3db.png)

![screen shot 2017-04-11 at 12 03 39](https://cloud.githubusercontent.com/assets/2204224/24906350/490a1f0e-1eaf-11e7-9c77-ff6a9936d10c.png)

Publishing Frontend Support: https://trello.com/c/VVGQ6axB/61-layout-for-feedback-slightly-broken

**Comment by alecgibson** [comment]
It should be noted that this is because the wrapper for this JS link is [inside a site-width wrapper](https://github.com/alphagov/static/blob/master/app/assets/stylesheets/helpers/_report-a-problem.scss#L88-L91).

This is fine on pages where the link is not contained in a wrapper (eg https://www.gov.uk/), but doesn't work on pages where the link is contained inside another wrapper that's already set to site-width (eg https://www.gov.uk/education).

The huge problem is that all the frontend apps are inconsistent with whether or not they put this element in a wrapper or not. I've heard it said that govuk-components should entirely fill their container, which means we should probably remove the site-width wrapper from the link, but we'd have to then go and make sure that all frontend apps that render the link (ie every page on GOV.UK?!) puts this link inside a wrapper.

**Comment by fofr** [comment]
A previous attempt to fix: https://github.com/alphagov/static/pull/660
That got reverted: https://github.com/alphagov/static/pull/662

**Comment by alecgibson** [comment]
Also note that I set up a [Wraith config](https://github.com/alecgibson/govuk-wraith-results/tree/8d721cd3229a5e9445ac49b13d9a2ad5c8390862) to diff page histories for all types of document type, which might be useful.
